--!strict
-- Uploaded UI artwork (generated by tools/make_icons.py; white glyph + baked dark outline,
-- tint with ImageColor3). Source PNGs are kept in assets/icons/.
return {
	power = "rbxassetid://106826911256962",
	food = "rbxassetid://88125430882704",
	water = "rbxassetid://134078787006777",
	bolts = "rbxassetid://91021163094854",
	happy = "rbxassetid://104356492105746",
	population = "rbxassetid://104915652934632",
	survivors = "rbxassetid://133129409590661",
	build = "rbxassetid://91601171714117",
	weapons = "rbxassetid://130017130410866",
	outfits = "rbxassetid://106350143470017",
	quests = "rbxassetid://93981386742819",
	shop = "rbxassetid://86739434948721",
	rush = "rbxassetid://107302663950390",
	upgrade = "rbxassetid://114974746390746",
	close = "rbxassetid://110411779350080",
	info = "rbxassetid://101963010477578",
	fire = "rbxassetid://87668791553480",
	raid = "rbxassetid://136549225377246",
	health = "rbxassetid://117046560643029",
	star = "rbxassetid://115026470064527",
	assign = "rbxassetid://74306333294434",
	level = "rbxassetid://108050543101165",
	wasteland = "rbxassetid://86894212231033",
	panel = "rbxassetid://88388094384059", -- 9-slice 128px, slice 24
	button = "rbxassetid://107158111270975", -- 9-slice 128px, slice 28
}
