--!strict
-- Sound cues: which piece of the audio atlas each game event plays, how loud, how much the pitch
-- wanders and how often it may repeat. The atlas (audio/underhaven_sounds.ogg) and its region
-- map (Shared/SoundAtlas) are generated by tools/make_sounds.py; every sound in it is original.
--
-- Roblox keeps audio outside the place file, so upload audio/underhaven_sounds.ogg ONCE and
-- paste its id below (Studio: Window > Asset Manager > Bulk Import, or tools/upload_sounds.py).
-- Until then the game simply stays silent.
local SoundBank = {}

SoundBank.ATLAS_ID = "" -- e.g. "rbxassetid://1234567890"

-- group: "UI" and "SFX" follow the Sound effects toggle, "Ambience" the Ambience toggle.
-- pitch: random +/- share per play. cooldown: seconds before the same cue may play again.
export type Cue = { region: string, group: string, volume: number, pitch: number?, cooldown: number? }

SoundBank.Cues = {
	-- interface
	click = { region = "ui_click", group = "UI", volume = 0.3, pitch = 0.05, cooldown = 0.05 },
	open = { region = "ui_open", group = "UI", volume = 0.28, cooldown = 0.12 },
	close = { region = "ui_close", group = "UI", volume = 0.22, cooldown = 0.12 },
	error = { region = "ui_error", group = "UI", volume = 0.32, cooldown = 0.3 },
	-- economy and building
	collect = { region = "collect", group = "SFX", volume = 0.5, pitch = 0.06, cooldown = 0.08 },
	bolts = { region = "bolts", group = "SFX", volume = 0.35, pitch = 0.04, cooldown = 0.1 },
	build = { region = "build", group = "SFX", volume = 0.55, cooldown = 0.3 },
	upgrade = { region = "upgrade", group = "SFX", volume = 0.5, cooldown = 0.3 },
	demolish = { region = "demolish", group = "SFX", volume = 0.55, cooldown = 0.3 },
	rush = { region = "rush", group = "SFX", volume = 0.45, cooldown = 0.3 },
	-- people
	levelup = { region = "levelup", group = "SFX", volume = 0.45, cooldown = 0.4 },
	heal = { region = "heal", group = "SFX", volume = 0.4, cooldown = 0.2 },
	revive = { region = "revive", group = "SFX", volume = 0.5, cooldown = 0.3 },
	doorbell = { region = "doorbell", group = "SFX", volume = 0.45, cooldown = 2 },
	welcome = { region = "welcome", group = "SFX", volume = 0.4, cooldown = 0.3 },
	birth = { region = "birth", group = "SFX", volume = 0.45, cooldown = 0.5 },
	romance = { region = "romance", group = "SFX", volume = 0.35, cooldown = 1 },
	death = { region = "death", group = "SFX", volume = 0.55, cooldown = 0.5 },
	-- emergencies and combat
	fire_start = { region = "fire_start", group = "SFX", volume = 0.55, cooldown = 0.3 },
	extinguish = { region = "extinguish", group = "SFX", volume = 0.45, cooldown = 0.3 },
	breakdown = { region = "breakdown", group = "SFX", volume = 0.55, cooldown = 0.3 },
	repair_done = { region = "repair_done", group = "SFX", volume = 0.45, cooldown = 0.3 },
	creature = { region = "creature", group = "SFX", volume = 0.35, pitch = 0.12, cooldown = 0.5 },
	gunshot = { region = "gunshot", group = "SFX", volume = 0.3, pitch = 0.08, cooldown = 0.04 },
	punch = { region = "punch", group = "SFX", volume = 0.3, pitch = 0.1, cooldown = 0.04 },
	door_hit = { region = "door_hit", group = "SFX", volume = 0.5, pitch = 0.05, cooldown = 0.6 },
	door_breach = { region = "door_breach", group = "SFX", volume = 0.7, cooldown = 1 },
	raid_win = { region = "raid_win", group = "SFX", volume = 0.5, cooldown = 1 },
	raid_lose = { region = "raid_lose", group = "SFX", volume = 0.5, cooldown = 1 },
} :: { [string]: Cue }

-- Continuous beds; SoundController fades them with what's on screen.
SoundBank.Loops = {
	vault = { region = "amb_vault", group = "Ambience", volume = 0.45 },
	power = { region = "hum_power", group = "Ambience", volume = 0.3 },
	water = { region = "hum_water", group = "Ambience", volume = 0.3 },
	fire = { region = "fire", group = "SFX", volume = 0.4 },
	alarm = { region = "alarm", group = "SFX", volume = 0.3 },
} :: { [string]: Cue }

-- Gunshot pitch per weapon (heavier guns sound lower).
SoundBank.WeaponPitch = {
	ScrapPistol = 1.05,
	ScrapRevolver = 0.95,
	PipeRifle = 0.88,
	ImprovisedShotgun = 0.72,
	IndustrialSMG = 1.2,
	MakeshiftRifle = 0.82,
	EnergyCarbine = 1.35,
}

return SoundBank
