"""Export the solved animations as Luau data for the Phase 2 runtime pose driver.

    python3 blender_scripts/export_roblox.py

Writes ../../Phase2_CombatSystem/src/shared/Combat/{RigData,Clips}.luau and
AnimData/<Clip>.luau.  Every frame stores, per bone, the bone's world-space
delta rotation from rest (quaternion, Roblox axes) plus the pelvis offset, so
the runtime can rebuild Motor6D.Transform for ANY imported R15 rig by reading
that rig's own C0/C1 (no dependence on importer conventions).
"""
import json
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import bpy  # noqa: E402
from mathutils import Matrix, Vector  # noqa: E402

bpy.ops.wm.read_factory_settings(use_empty=True)

import anim  # noqa: E402
import clips as C  # noqa: E402
import meshes  # noqa: E402
import rig as R  # noqa: E402

OUT = os.path.join(os.path.dirname(os.path.dirname(HERE)), "Phase2_CombatSystem", "src", "shared", "Combat")
B2R = Matrix(((-1, 0, 0), (0, 0, 1), (0, 1, 0)))   # Blender (faces -Y) -> Roblox (faces -Z)
BONES = [b[0] for b in R.BONES[2:]] + ["SwordHandle", "BowHandle"]   # parents before children
UPPER = {"UpperTorso", "Head", "LeftUpperArm", "LeftLowerArm", "LeftHand", "RightUpperArm",
         "RightLowerArm", "RightHand", "SwordHandle", "BowHandle"}


def v(p):
    q = B2R @ Vector(p)
    return (q.x, q.y, q.z)


def fmt(x):
    s = "%.4f" % x
    s = s.rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def vec_lua(p):
    return "Vector3.new(%s, %s, %s)" % tuple(fmt(c) for c in v(p))


_top, _bot = meshes.bow_string_points()
STRING_REST = Vector((0, _top.y, meshes.BOW_NOCK_Z))


def prop_track(pose):
    """Arrow + bowstring state for one frame, in armature space."""
    P = pose.info["P"]
    b_pos, b_rot = pose.info["bow_world"]
    nock = STRING_REST.copy()
    if P["string_held"]:
        local = b_rot.inverted() @ (Vector(P["draw_pos"]) - b_pos)
        if local.y > STRING_REST.y:
            nock = local
    nock_w = b_pos + b_rot @ nock
    rest_pt = b_pos + b_rot @ Vector(meshes.ARROW_REST)
    state = P["arrow"]
    held = 1 if (P["string_held"] and (nock - STRING_REST).length > 1e-4) else 0
    if state == "nocked":
        origin, d, mode = nock_w, (rest_pt - nock_w).normalized(), 2
    elif state == "hand":
        origin = pose.mats["RightHand"] @ Vector((0, R.FIST + 0.04, 0))
        d, mode = Vector(P["arrow_dir"]).normalized(), 1
    else:
        origin, d, mode = nock_w, Vector((0, -1, 0)), 0
    return mode, held, origin, d, nock_w


def export_clip(clip, rest):
    lines = []
    st = {}
    props = []
    for f in range(clip.start, clip.end + 1):
        pose = anim.solve(clip.sample(f), rest, st)
        row = []
        for b in BONES:
            q = (B2R @ pose.delta[b] @ B2R.transposed()).to_quaternion()
            if q.w < 0:
                q = -q
            row += [q.x, q.y, q.z, q.w]
        off = pose.mats["LowerTorso"].translation - rest["LowerTorso"].translation
        row += list(v(off))
        lines.append(", ".join(fmt(x) for x in row))
        if clip.category == "BOW" or clip.name.startswith("Bow_"):
            mode, held, o, d, sp = prop_track(pose)
            props.append(", ".join(fmt(x) for x in [mode, held, *v(o), *v(d), *v(sp)]))
    src = ["-- Generated by Phase1_CombatAssets/blender_scripts/export_roblox.py. Do not edit.",
           "-- %s: %d frames @ %d fps. Per frame: %d bones x quaternion(x,y,z,w) + pelvis offset(x,y,z)."
           % (clip.name, clip.length + 1, anim.FPS, len(BONES)),
           "return {", "\tframes = %d," % (clip.length + 1), "\tdata = {"]
    src += ["\t\t%s," % ln for ln in lines]
    src.append("\t},")
    if props:
        src.append("\t-- per frame: arrowMode(0 none/1 in hand/2 nocked), stringHeld, arrowNock(xyz), arrowDir(xyz), stringPoint(xyz)")
        src.append("\tprops = {")
        src += ["\t\t%s," % ln for ln in props]
        src.append("\t},")
    src.append("}")
    return "\n".join(src) + "\n"


def main():
    os.makedirs(os.path.join(OUT, "AnimData"), exist_ok=True)
    rig_ob = R.build_armature("R15_Rig")
    rest = R.rest_matrices(rig_ob)
    all_clips = C.all_clips()

    # ---- AnimData
    for clip in all_clips:
        with open(os.path.join(OUT, "AnimData", clip.name + ".luau"), "w") as fh:
            fh.write(export_clip(clip, rest))

    # ---- Clips manifest
    L = ["-- Generated. Clip metadata: length (s), loop, markers (s), category, upper-body layerable.",
         "return {", "\tfps = %d," % anim.FPS, "\tlocoSpeed = %s," % fmt(C.LOCO_SPEED), "\tclips = {"]
    upper_ok = {"Sword_Block", "Sword_Block_Hold", "Sword_Block_Recover", "Bow_Nock", "Bow_Draw",
                "Bow_FullDraw", "Bow_Aim", "Bow_Release", "Bow_Lower"}
    for c in all_clips:
        mk = ", ".join('%s = %s' % (k, fmt(fr / anim.FPS)) for k, fr in sorted(c.markers.items(), key=lambda kv: kv[1]))
        L.append('\t\t%s = { length = %s, loop = %s, category = "%s", upperBody = %s, markers = { %s } },' % (
            c.name, fmt(c.length / anim.FPS), str(c.loop).lower(), c.category,
            str(c.name in upper_ok).lower(), mk))
    L += ["\t},", "}"]
    with open(os.path.join(OUT, "Clips.luau"), "w") as fh:
        fh.write("\n".join(L) + "\n")

    # ---- Rig data: bone order, parents, rest pivots, reference points
    parent = {b[0]: b[1] for b in R.BONES}
    parent["SwordHandle"], parent["BowHandle"] = "RightHand", "LeftHand"
    s = meshes.SWORD
    blade0 = s["grip_top"] + s["guard_h"]
    sw = lambda z: R.SWORD_REST_POS + R.SWORD_REST_FRAME @ Vector((0, 0, z))
    bw = lambda p: R.BOW_REST_POS + R.BOW_REST_FRAME @ Vector(p)
    wrist_r = Vector((-R.SX, 0, R.Z_WRIST))
    points = {
        # name = (anchor bone, rest position)
        "BladeBase": ("SwordHandle", sw(blade0)),
        "BladeMid": ("SwordHandle", sw(blade0 + s["blade_len"] * 0.5)),
        "BladeTip": ("SwordHandle", sw(blade0 + s["blade_len"])),
        "BowUpperNock": ("BowHandle", bw((0, _top.y, _top.z))),
        "BowLowerNock": ("BowHandle", bw((0, _top.y, -_top.z))),
        "BowStringRest": ("BowHandle", bw(STRING_REST)),
        "BowArrowRest": ("BowHandle", bw(meshes.ARROW_REST)),
        "RightFingers": ("RightHand", wrist_r + Vector((0, 0, -0.30))),
    }
    L = ["-- Generated. Rest-pose rig description in Roblox axes (character faces -Z).",
         "-- Pivots are joint positions (bone heads) in the authoring rig's space;",
         "-- the runtime maps them onto the live rig via RightShoulder/LeftShoulder/Neck.",
         "return {",
         "\tbones = { %s }," % ", ".join('"%s"' % b for b in BONES),
         "\tparent = { %s }," % ", ".join('%s = "%s"' % (b, parent[b] if parent[b] != "HumanoidRootNode" else "HumanoidRootPart") for b in BONES),
         "\tupper = { %s }," % ", ".join("%s = true" % b for b in BONES if b in UPPER),
         "\tpivot = {"]
    for b in BONES:
        L.append("\t\t%s = %s," % (b, vec_lua(rest[b].translation)))
    L.append("\t},")
    L.append("\tpoints = {")
    for n, (bone, p) in points.items():
        L.append('\t\t%s = { bone = "%s", pos = %s },' % (n, bone, vec_lua(p)))
    L.append("\t},")
    # hurtboxes: rest-pose bounding box of each body mesh (authoring space, Roblox axes)
    body = R.build_body(rig_ob)
    L.append("\thurtboxes = {")
    for bone, ob in body.items():
        vs = [ob.matrix_world @ vv.co for vv in ob.data.vertices]
        lo = Vector([min(p[i] for p in vs) for i in range(3)])
        hi = Vector([max(p[i] for p in vs) for i in range(3)])
        c = (lo + hi) / 2
        sz = hi - lo
        L.append("\t\t%s = { center = %s, size = Vector3.new(%s, %s, %s) }," % (
            bone, vec_lua(c), fmt(sz.x), fmt(sz.z), fmt(sz.y)))
    L.append("\t},")
    # weapon grip frames at rest. Weapon-local Roblox axes: +Y = blade / upper limb,
    # sword -X = true edge, bow +Z = string side. Columns are authoring-space directions.
    def wframe(pos, F):
        cols = [F @ Vector((-1, 0, 0)), F @ Vector((0, 0, 1)), F @ Vector((0, 1, 0))]
        return "CFrame.fromMatrix(%s, %s, %s, %s)" % (vec_lua(pos), *(vec_lua(c) for c in cols))
    L.append("\tweapons = {")
    L.append('\t\tSword = { bone = "SwordHandle", fallback = "RightHand", rest = %s },' % wframe(R.SWORD_REST_POS, R.SWORD_REST_FRAME))
    L.append('\t\tBow = { bone = "BowHandle", fallback = "LeftHand", rest = %s },' % wframe(R.BOW_REST_POS, R.BOW_REST_FRAME))
    L.append("\t},")
    sw = meshes.SWORD
    L.append("\tswordDims = { gripTop = %s, guardH = %s, bladeLen = %s, bladeW0 = %s, bladeW1 = %s, bladeT = %s, "
             "gripLen = %s, gripR = %s, guardSpan = %s, pommelR = %s }," % tuple(fmt(x) for x in (
                 sw["grip_top"], sw["guard_h"], sw["blade_len"], sw["blade_w0"], sw["blade_w1"], sw["blade_t0"],
                 sw["grip_len"], sw["grip_rx"], sw["guard_span"], sw["pommel_r"])))
    bw = meshes.BOW
    curve = []
    for i in range(-12, 13):
        z = bw["half_len"] * i / 12
        curve.append("{ %s, %s }" % (fmt(z), fmt(meshes.bow_centerline(z))))
    L.append("\t-- bow centreline in weapon space: { along limb (+Y), toward string (+Z) }")
    L.append("\tbowCurve = { %s }," % ", ".join(curve))
    L.append("\tbowDims = { wGrip = %s, dGrip = %s, wTip = %s, dTip = %s, gripHalf = %s }," % tuple(fmt(x) for x in (
        bw["w_grip"], bw["d_grip"], bw["w_tip"], bw["d_tip"], bw["grip_half"])))
    L.append("\tstudsPerMetre = %s," % fmt(meshes.M))
    L.append("\tarrowLength = %s," % fmt(meshes.ARROW["length"] + 0.3))
    L.append("}")
    with open(os.path.join(OUT, "RigData.luau"), "w") as fh:
        fh.write("\n".join(L) + "\n")

    # reference poses for the Luau unit test: posed pivots at a few frames
    ref = {}
    for name, frames in (("Sword_Attack_HighRight", (0, 18)), ("Bow_FullDraw", (0,))):
        clip = next(c for c in all_clips if c.name == name)
        st = {}
        poses = {}
        for f in range(clip.start, max(frames) + 1):   # same temporal state as the export
            poses[f] = anim.solve(clip.sample(f), rest, st)
        for f in frames:
            pose = poses[f]
            ref["%s@%d" % (name, f)] = {b: v(pose.mats[b].translation) for b in BONES}
            if clip.category != "BOW":
                pos, rot = pose.info["sword_world"]
                ref["%s@%d" % (name, f)]["_BladeTip"] = v(pos + rot @ Vector((0, 0, blade0 + s["blade_len"])))
    tdir = os.path.join(os.path.dirname(os.path.dirname(OUT)), "..", "tests")
    os.makedirs(tdir, exist_ok=True)
    with open(os.path.join(tdir, "reference_poses.json"), "w") as fh:
        json.dump(ref, fh, indent=1)
    print("exported %d clips -> %s" % (len(all_clips), OUT))


if __name__ == "__main__":
    main()
